### ISSUE TITLE
main.py error

### ISSUE THREAD

**Issue by jphconstantin** [marcanuy/publishfeed#5]
Hello,
I try to use your tool but not easy ...

When I execute:
`python main.py f_f_meyrin --getfeeds`

 I have this error:
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from helpers import RSSContentHelper, FeedSetHelper
  File "/home/jpc/virtual-project/publishfeed/helpers.py", line 2, in <module>
    from twitter import Twitter
  File "/home/jpc/virtual-project/publishfeed/twitter.py", line 1, in <module>
    import tweepy
  File "/home/jpc/virtual-project/lib/python3.7/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/home/jpc/virtual-project/lib/python3.7/site-packages/tweepy/streaming.py", line 355
    def _start(self, async):
                         ^
SyntaxError: invalid syntax

Any idea of the reason ?

**Comment by marcanuy** [comment]
It currently uses an outdated tweepy version which has [problems](https://github.com/tweepy/tweepy/issues/1017) with python 3.7, upgrading that dependency should fix that.

**Comment by jphconstantin** [comment]
I must modifiy the requirements.txt file:

3.5.0 -> 3.10.0

**Comment by jphconstantin** [comment]
OK
